 SELECT  
        REPLACE(Pat.[NHS_NBR_IDENT],'-','')							AS [NHS_Number]   
        ,CAST(Pat.BIRTH_DT_TM AS DATE)								AS [Date_of_Birth]
		,Gend.ALIAS_NHS_CD_ALIAS									AS [GENDER_CD]
        ,GEND.CODE_DISP_TXT											AS [Gender] 
		,Eth.ALIAS_NHS_CD_ALIAS										AS [ETHNIC_CD]
        ,Eth.CODE_DESC_TXT											AS [Ethnicity]
        ,Pat.DECEASED_DT_TM											AS [Date_of_Death]
        ,Pat.[PERSON_ID]
        ,Pat.LOCAL_PATIENT_IDENT									AS [MRN]
		,(SELECT TOP(1) POSTCODE_TXT FROM [BH_DATAWAREHOUSE].[dbo].[PI_CDE_PERSON_PATIENT_ADDRESS] A WHERE A.PERSON_ID = Pat.PERSON_ID ORDER BY END_EFFECTIVE_DT_TM  DESC) AS [Postcode]
		,(SELECT TOP(1) CITY_TXT FROM [BH_DATAWAREHOUSE].[dbo].[PI_CDE_PERSON_PATIENT_ADDRESS] A WHERE A.PERSON_ID = Pat.PERSON_ID ORDER BY END_EFFECTIVE_DT_TM  DESC) AS [City]
		,MARITAL_STATUS_CD											AS [MARITAL_STATUS_CD]
		,Mart.CODE_DESC_TXT											AS [MARITAL_STATUS]
		,LANGUAGE_CD												AS [LANGUAGE_CD]
		,lang.CODE_DESC_TXT											AS [LANGUAGE]
		,RELIGION_CD												AS [RELIGION_CD]
		,Reli.CODE_DESC_TXT											AS [RELIGION]
     INTO  BH_RESEARCH.DBO.refactored_RDE_Patient_Demographics

    FROM  [BH_DATAWAREHOUSE].[dbo].[PI_CDE_PERSON_PATIENT] Pat with (nolock)
          INNER JOIN [BH_RESEARCH].[dbo].[RESEARCH_PATIENTS] Res
               --ON  REPLACE(Pat.[NHS_NBR_IDENT],'-','')=Res.NHS_Number
			   ON PAT.PERSON_ID=RES.PERSONID
	      LEFT OUTER JOIN [BH_DATAWAREHOUSE].DBO.[PI_LKP_CDE_CODE_VALUE_REF] Eth with (nolock)
               ON Pat.ETHNIC_GROUP_CD=Eth.CODE_VALUE_CD
          LEFT OUTER JOIN [BH_DATAWAREHOUSE].DBO.[PI_LKP_CDE_CODE_VALUE_REF] Gend with (nolock)
               ON Pat.GENDER_CD=Gend.CODE_VALUE_CD
          LEFT OUTER JOIN [BH_DATAWAREHOUSE].DBO.[PI_LKP_CDE_CODE_VALUE_REF] Mart with (nolock)
               ON Pat.MARITAL_STATUS_CD=Mart.CODE_VALUE_CD
		  LEFT OUTER JOIN [BH_DATAWAREHOUSE].DBO.[PI_LKP_CDE_CODE_VALUE_REF] lang with (nolock)
               ON Pat.LANGUAGE_CD=lang.CODE_VALUE_CD
		  LEFT OUTER JOIN [BH_DATAWAREHOUSE].DBO.[PI_LKP_CDE_CODE_VALUE_REF] Reli with (nolock)
               ON Pat.RELIGION_CD=Reli.CODE_VALUE_CD
    WHERE RES.EXTRACT_ID=@EXTRACT_ID